// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen with some manual edits:
// - Remove regiser functions, we don't need them.
// - Remove uncessary conversion functions (e.g. Convert_v2_MonitoringV1Client_To_v1_MonitoringV1Client).
// TODO: Automate all the things.

package v2

import (
	unsafe "unsafe"

	v1 "github.com/coreos/prometheus-operator/pkg/client/monitoring/v1"
	core_v1 "k8s.io/api/core/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
)

func autoConvert_v2_AlertingSpec_To_v1_AlertingSpec(in *AlertingSpec, out *v1.AlertingSpec, s conversion.Scope) error {
	out.Alertmanagers = *(*[]v1.AlertmanagerEndpoints)(unsafe.Pointer(&in.Alertmanagers))
	return nil
}

// Convert_v2_AlertingSpec_To_v1_AlertingSpec is an autogenerated conversion function.
func Convert_v2_AlertingSpec_To_v1_AlertingSpec(in *AlertingSpec, out *v1.AlertingSpec, s conversion.Scope) error {
	return autoConvert_v2_AlertingSpec_To_v1_AlertingSpec(in, out, s)
}

func autoConvert_v1_AlertingSpec_To_v2_AlertingSpec(in *v1.AlertingSpec, out *AlertingSpec, s conversion.Scope) error {
	out.Alertmanagers = *(*[]AlertmanagerEndpoints)(unsafe.Pointer(&in.Alertmanagers))
	return nil
}

// Convert_v1_AlertingSpec_To_v2_AlertingSpec is an autogenerated conversion function.
func Convert_v1_AlertingSpec_To_v2_AlertingSpec(in *v1.AlertingSpec, out *AlertingSpec, s conversion.Scope) error {
	return autoConvert_v1_AlertingSpec_To_v2_AlertingSpec(in, out, s)
}

func autoConvert_v2_Alertmanager_To_v1_Alertmanager(in *Alertmanager, out *v1.Alertmanager, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_AlertmanagerSpec_To_v1_AlertmanagerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*v1.AlertmanagerStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v2_Alertmanager_To_v1_Alertmanager is an autogenerated conversion function.
func Convert_v2_Alertmanager_To_v1_Alertmanager(in *Alertmanager, out *v1.Alertmanager, s conversion.Scope) error {
	return autoConvert_v2_Alertmanager_To_v1_Alertmanager(in, out, s)
}

func autoConvert_v1_Alertmanager_To_v2_Alertmanager(in *v1.Alertmanager, out *Alertmanager, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_AlertmanagerSpec_To_v2_AlertmanagerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*AlertmanagerStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1_Alertmanager_To_v2_Alertmanager is an autogenerated conversion function.
func Convert_v1_Alertmanager_To_v2_Alertmanager(in *v1.Alertmanager, out *Alertmanager, s conversion.Scope) error {
	return autoConvert_v1_Alertmanager_To_v2_Alertmanager(in, out, s)
}

func autoConvert_v2_AlertmanagerEndpoints_To_v1_AlertmanagerEndpoints(in *AlertmanagerEndpoints, out *v1.AlertmanagerEndpoints, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Port = in.Port
	out.Scheme = in.Scheme
	out.PathPrefix = in.PathPrefix
	return nil
}

// Convert_v2_AlertmanagerEndpoints_To_v1_AlertmanagerEndpoints is an autogenerated conversion function.
func Convert_v2_AlertmanagerEndpoints_To_v1_AlertmanagerEndpoints(in *AlertmanagerEndpoints, out *v1.AlertmanagerEndpoints, s conversion.Scope) error {
	return autoConvert_v2_AlertmanagerEndpoints_To_v1_AlertmanagerEndpoints(in, out, s)
}

func autoConvert_v1_AlertmanagerEndpoints_To_v2_AlertmanagerEndpoints(in *v1.AlertmanagerEndpoints, out *AlertmanagerEndpoints, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Port = in.Port
	out.Scheme = in.Scheme
	out.PathPrefix = in.PathPrefix
	return nil
}

// Convert_v1_AlertmanagerEndpoints_To_v2_AlertmanagerEndpoints is an autogenerated conversion function.
func Convert_v1_AlertmanagerEndpoints_To_v2_AlertmanagerEndpoints(in *v1.AlertmanagerEndpoints, out *AlertmanagerEndpoints, s conversion.Scope) error {
	return autoConvert_v1_AlertmanagerEndpoints_To_v2_AlertmanagerEndpoints(in, out, s)
}

func autoConvert_v2_AlertmanagerList_To_v1_AlertmanagerList(in *AlertmanagerList, out *v1.AlertmanagerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1.Alertmanager)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_AlertmanagerList_To_v1_AlertmanagerList is an autogenerated conversion function.
func Convert_v2_AlertmanagerList_To_v1_AlertmanagerList(in *AlertmanagerList, out *v1.AlertmanagerList, s conversion.Scope) error {
	return autoConvert_v2_AlertmanagerList_To_v1_AlertmanagerList(in, out, s)
}

func autoConvert_v1_AlertmanagerList_To_v2_AlertmanagerList(in *v1.AlertmanagerList, out *AlertmanagerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Alertmanager)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_AlertmanagerList_To_v2_AlertmanagerList is an autogenerated conversion function.
func Convert_v1_AlertmanagerList_To_v2_AlertmanagerList(in *v1.AlertmanagerList, out *AlertmanagerList, s conversion.Scope) error {
	return autoConvert_v1_AlertmanagerList_To_v2_AlertmanagerList(in, out, s)
}

func autoConvert_v2_AlertmanagerSpec_To_v1_AlertmanagerSpec(in *AlertmanagerSpec, out *v1.AlertmanagerSpec, s conversion.Scope) error {
	out.PodMetadata = (*meta_v1.ObjectMeta)(unsafe.Pointer(in.PodMetadata))
	out.Version = in.Version
	out.BaseImage = in.BaseImage
	out.ImagePullSecrets = *(*[]core_v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Storage = (*v1.StorageSpec)(unsafe.Pointer(in.Storage))
	out.ExternalURL = in.ExternalURL
	out.RoutePrefix = in.RoutePrefix
	out.Paused = in.Paused
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Resources = in.Resources
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v2_AlertmanagerSpec_To_v1_AlertmanagerSpec is an autogenerated conversion function.
func Convert_v2_AlertmanagerSpec_To_v1_AlertmanagerSpec(in *AlertmanagerSpec, out *v1.AlertmanagerSpec, s conversion.Scope) error {
	return autoConvert_v2_AlertmanagerSpec_To_v1_AlertmanagerSpec(in, out, s)
}

func autoConvert_v1_AlertmanagerSpec_To_v2_AlertmanagerSpec(in *v1.AlertmanagerSpec, out *AlertmanagerSpec, s conversion.Scope) error {
	out.PodMetadata = (*meta_v1.ObjectMeta)(unsafe.Pointer(in.PodMetadata))
	out.Version = in.Version
	out.BaseImage = in.BaseImage
	out.ImagePullSecrets = *(*[]core_v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Storage = (*StorageSpec)(unsafe.Pointer(in.Storage))
	out.ExternalURL = in.ExternalURL
	out.RoutePrefix = in.RoutePrefix
	out.Paused = in.Paused
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.Resources = in.Resources
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1_AlertmanagerSpec_To_v2_AlertmanagerSpec is an autogenerated conversion function.
func Convert_v1_AlertmanagerSpec_To_v2_AlertmanagerSpec(in *v1.AlertmanagerSpec, out *AlertmanagerSpec, s conversion.Scope) error {
	return autoConvert_v1_AlertmanagerSpec_To_v2_AlertmanagerSpec(in, out, s)
}

func autoConvert_v2_AlertmanagerStatus_To_v1_AlertmanagerStatus(in *AlertmanagerStatus, out *v1.AlertmanagerStatus, s conversion.Scope) error {
	out.Paused = in.Paused
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_v2_AlertmanagerStatus_To_v1_AlertmanagerStatus is an autogenerated conversion function.
func Convert_v2_AlertmanagerStatus_To_v1_AlertmanagerStatus(in *AlertmanagerStatus, out *v1.AlertmanagerStatus, s conversion.Scope) error {
	return autoConvert_v2_AlertmanagerStatus_To_v1_AlertmanagerStatus(in, out, s)
}

func autoConvert_v1_AlertmanagerStatus_To_v2_AlertmanagerStatus(in *v1.AlertmanagerStatus, out *AlertmanagerStatus, s conversion.Scope) error {
	out.Paused = in.Paused
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_v1_AlertmanagerStatus_To_v2_AlertmanagerStatus is an autogenerated conversion function.
func Convert_v1_AlertmanagerStatus_To_v2_AlertmanagerStatus(in *v1.AlertmanagerStatus, out *AlertmanagerStatus, s conversion.Scope) error {
	return autoConvert_v1_AlertmanagerStatus_To_v2_AlertmanagerStatus(in, out, s)
}

func autoConvert_v2_BasicAuth_To_v1_BasicAuth(in *BasicAuth, out *v1.BasicAuth, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v2_BasicAuth_To_v1_BasicAuth is an autogenerated conversion function.
func Convert_v2_BasicAuth_To_v1_BasicAuth(in *BasicAuth, out *v1.BasicAuth, s conversion.Scope) error {
	return autoConvert_v2_BasicAuth_To_v1_BasicAuth(in, out, s)
}

func autoConvert_v1_BasicAuth_To_v2_BasicAuth(in *v1.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	out.Username = in.Username
	out.Password = in.Password
	return nil
}

// Convert_v1_BasicAuth_To_v2_BasicAuth is an autogenerated conversion function.
func Convert_v1_BasicAuth_To_v2_BasicAuth(in *v1.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	return autoConvert_v1_BasicAuth_To_v2_BasicAuth(in, out, s)
}

func autoConvert_v2_Endpoint_To_v1_Endpoint(in *Endpoint, out *v1.Endpoint, s conversion.Scope) error {
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	out.Path = in.Path
	out.Scheme = in.Scheme
	out.Params = *(*map[string][]string)(unsafe.Pointer(&in.Params))
	out.Interval = in.Interval
	out.ScrapeTimeout = in.ScrapeTimeout
	out.TLSConfig = (*v1.TLSConfig)(unsafe.Pointer(in.TLSConfig))
	out.BearerTokenFile = in.BearerTokenFile
	out.HonorLabels = in.HonorLabels
	out.BasicAuth = (*v1.BasicAuth)(unsafe.Pointer(in.BasicAuth))
	return nil
}

// Convert_v2_Endpoint_To_v1_Endpoint is an autogenerated conversion function.
func Convert_v2_Endpoint_To_v1_Endpoint(in *Endpoint, out *v1.Endpoint, s conversion.Scope) error {
	return autoConvert_v2_Endpoint_To_v1_Endpoint(in, out, s)
}

func autoConvert_v1_Endpoint_To_v2_Endpoint(in *v1.Endpoint, out *Endpoint, s conversion.Scope) error {
	out.Port = in.Port
	out.TargetPort = in.TargetPort
	out.Path = in.Path
	out.Scheme = in.Scheme
	out.Params = *(*map[string][]string)(unsafe.Pointer(&in.Params))
	out.Interval = in.Interval
	out.ScrapeTimeout = in.ScrapeTimeout
	out.TLSConfig = (*TLSConfig)(unsafe.Pointer(in.TLSConfig))
	out.BearerTokenFile = in.BearerTokenFile
	out.HonorLabels = in.HonorLabels
	out.BasicAuth = (*BasicAuth)(unsafe.Pointer(in.BasicAuth))
	return nil
}

// Convert_v1_Endpoint_To_v2_Endpoint is an autogenerated conversion function.
func Convert_v1_Endpoint_To_v2_Endpoint(in *v1.Endpoint, out *Endpoint, s conversion.Scope) error {
	return autoConvert_v1_Endpoint_To_v2_Endpoint(in, out, s)
}

func autoConvert_v2_NamespaceSelector_To_v1_NamespaceSelector(in *NamespaceSelector, out *v1.NamespaceSelector, s conversion.Scope) error {
	out.Any = in.Any
	out.MatchNames = *(*[]string)(unsafe.Pointer(&in.MatchNames))
	return nil
}

// Convert_v2_NamespaceSelector_To_v1_NamespaceSelector is an autogenerated conversion function.
func Convert_v2_NamespaceSelector_To_v1_NamespaceSelector(in *NamespaceSelector, out *v1.NamespaceSelector, s conversion.Scope) error {
	return autoConvert_v2_NamespaceSelector_To_v1_NamespaceSelector(in, out, s)
}

func autoConvert_v1_NamespaceSelector_To_v2_NamespaceSelector(in *v1.NamespaceSelector, out *NamespaceSelector, s conversion.Scope) error {
	out.Any = in.Any
	out.MatchNames = *(*[]string)(unsafe.Pointer(&in.MatchNames))
	return nil
}

// Convert_v1_NamespaceSelector_To_v2_NamespaceSelector is an autogenerated conversion function.
func Convert_v1_NamespaceSelector_To_v2_NamespaceSelector(in *v1.NamespaceSelector, out *NamespaceSelector, s conversion.Scope) error {
	return autoConvert_v1_NamespaceSelector_To_v2_NamespaceSelector(in, out, s)
}

func autoConvert_v2_Prometheus_To_v1_Prometheus(in *Prometheus, out *v1.Prometheus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_PrometheusSpec_To_v1_PrometheusSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*v1.PrometheusStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v2_Prometheus_To_v1_Prometheus is an autogenerated conversion function.
func Convert_v2_Prometheus_To_v1_Prometheus(in *Prometheus, out *v1.Prometheus, s conversion.Scope) error {
	return autoConvert_v2_Prometheus_To_v1_Prometheus(in, out, s)
}

func autoConvert_v1_Prometheus_To_v2_Prometheus(in *v1.Prometheus, out *Prometheus, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_PrometheusSpec_To_v2_PrometheusSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = (*PrometheusStatus)(unsafe.Pointer(in.Status))
	return nil
}

// Convert_v1_Prometheus_To_v2_Prometheus is an autogenerated conversion function.
func Convert_v1_Prometheus_To_v2_Prometheus(in *v1.Prometheus, out *Prometheus, s conversion.Scope) error {
	return autoConvert_v1_Prometheus_To_v2_Prometheus(in, out, s)
}

func autoConvert_v2_PrometheusList_To_v1_PrometheusList(in *PrometheusList, out *v1.PrometheusList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*v1.Prometheus, len(*in))
		for i := range *in {
			// TODO: Inefficient conversion - can we improve it?
			if err := s.Convert(&(*in)[i], &(*out)[i], 0); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v2_PrometheusList_To_v1_PrometheusList is an autogenerated conversion function.
func Convert_v2_PrometheusList_To_v1_PrometheusList(in *PrometheusList, out *v1.PrometheusList, s conversion.Scope) error {
	return autoConvert_v2_PrometheusList_To_v1_PrometheusList(in, out, s)
}

func autoConvert_v1_PrometheusList_To_v2_PrometheusList(in *v1.PrometheusList, out *PrometheusList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*Prometheus, len(*in))
		for i := range *in {
			// TODO: Inefficient conversion - can we improve it?
			if err := s.Convert(&(*in)[i], &(*out)[i], 0); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1_PrometheusList_To_v2_PrometheusList is an autogenerated conversion function.
func Convert_v1_PrometheusList_To_v2_PrometheusList(in *v1.PrometheusList, out *PrometheusList, s conversion.Scope) error {
	return autoConvert_v1_PrometheusList_To_v2_PrometheusList(in, out, s)
}

func autoConvert_v2_PrometheusSpec_To_v1_PrometheusSpec(in *PrometheusSpec, out *v1.PrometheusSpec, s conversion.Scope) error {
	out.PodMetadata = (*meta_v1.ObjectMeta)(unsafe.Pointer(in.PodMetadata))
	out.ServiceMonitorSelector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.ServiceMonitorSelector))
	out.Version = in.Version
	out.Paused = in.Paused
	out.BaseImage = in.BaseImage
	out.ImagePullSecrets = *(*[]core_v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Retention = in.Retention
	out.ScrapeInterval = in.ScrapeInterval
	out.EvaluationInterval = in.EvaluationInterval
	out.ExternalLabels = *(*map[string]string)(unsafe.Pointer(&in.ExternalLabels))
	out.ExternalURL = in.ExternalURL
	out.RoutePrefix = in.RoutePrefix
	out.Storage = (*v1.StorageSpec)(unsafe.Pointer(in.Storage))
	out.RuleSelector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.RuleSelector))
	if err := Convert_v2_AlertingSpec_To_v1_AlertingSpec(&in.Alerting, &out.Alerting, s); err != nil {
		return err
	}
	// WARNING: in.RemoteWrite requires manual conversion: does not exist in peer-type
	// WARNING: in.RemoteRead requires manual conversion: does not exist in peer-type
	out.Resources = in.Resources
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.ServiceAccountName = in.ServiceAccountName
	out.Secrets = *(*[]string)(unsafe.Pointer(&in.Secrets))
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

func autoConvert_v1_PrometheusSpec_To_v2_PrometheusSpec(in *v1.PrometheusSpec, out *PrometheusSpec, s conversion.Scope) error {
	out.PodMetadata = (*meta_v1.ObjectMeta)(unsafe.Pointer(in.PodMetadata))
	out.ServiceMonitorSelector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.ServiceMonitorSelector))
	out.Version = in.Version
	out.Paused = in.Paused
	out.BaseImage = in.BaseImage
	out.ImagePullSecrets = *(*[]core_v1.LocalObjectReference)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Replicas = (*int32)(unsafe.Pointer(in.Replicas))
	out.Retention = in.Retention
	out.ScrapeInterval = in.ScrapeInterval
	out.EvaluationInterval = in.EvaluationInterval
	out.ExternalLabels = *(*map[string]string)(unsafe.Pointer(&in.ExternalLabels))
	out.ExternalURL = in.ExternalURL
	out.RoutePrefix = in.RoutePrefix
	out.Storage = (*StorageSpec)(unsafe.Pointer(in.Storage))
	out.RuleSelector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.RuleSelector))
	if err := Convert_v1_AlertingSpec_To_v2_AlertingSpec(&in.Alerting, &out.Alerting, s); err != nil {
		return err
	}
	out.Resources = in.Resources
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.ServiceAccountName = in.ServiceAccountName
	out.Secrets = *(*[]string)(unsafe.Pointer(&in.Secrets))
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1_PrometheusSpec_To_v2_PrometheusSpec is an autogenerated conversion function.
func Convert_v1_PrometheusSpec_To_v2_PrometheusSpec(in *v1.PrometheusSpec, out *PrometheusSpec, s conversion.Scope) error {
	return autoConvert_v1_PrometheusSpec_To_v2_PrometheusSpec(in, out, s)
}

func autoConvert_v2_PrometheusStatus_To_v1_PrometheusStatus(in *PrometheusStatus, out *v1.PrometheusStatus, s conversion.Scope) error {
	out.Paused = in.Paused
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_v2_PrometheusStatus_To_v1_PrometheusStatus is an autogenerated conversion function.
func Convert_v2_PrometheusStatus_To_v1_PrometheusStatus(in *PrometheusStatus, out *v1.PrometheusStatus, s conversion.Scope) error {
	return autoConvert_v2_PrometheusStatus_To_v1_PrometheusStatus(in, out, s)
}

func autoConvert_v1_PrometheusStatus_To_v2_PrometheusStatus(in *v1.PrometheusStatus, out *PrometheusStatus, s conversion.Scope) error {
	out.Paused = in.Paused
	out.Replicas = in.Replicas
	out.UpdatedReplicas = in.UpdatedReplicas
	out.AvailableReplicas = in.AvailableReplicas
	out.UnavailableReplicas = in.UnavailableReplicas
	return nil
}

// Convert_v1_PrometheusStatus_To_v2_PrometheusStatus is an autogenerated conversion function.
func Convert_v1_PrometheusStatus_To_v2_PrometheusStatus(in *v1.PrometheusStatus, out *PrometheusStatus, s conversion.Scope) error {
	return autoConvert_v1_PrometheusStatus_To_v2_PrometheusStatus(in, out, s)
}

func autoConvert_v2_ServiceMonitor_To_v1_ServiceMonitor(in *ServiceMonitor, out *v1.ServiceMonitor, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v2_ServiceMonitorSpec_To_v1_ServiceMonitorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_ServiceMonitor_To_v1_ServiceMonitor is an autogenerated conversion function.
func Convert_v2_ServiceMonitor_To_v1_ServiceMonitor(in *ServiceMonitor, out *v1.ServiceMonitor, s conversion.Scope) error {
	return autoConvert_v2_ServiceMonitor_To_v1_ServiceMonitor(in, out, s)
}

func autoConvert_v1_ServiceMonitor_To_v2_ServiceMonitor(in *v1.ServiceMonitor, out *ServiceMonitor, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_ServiceMonitorSpec_To_v2_ServiceMonitorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ServiceMonitor_To_v2_ServiceMonitor is an autogenerated conversion function.
func Convert_v1_ServiceMonitor_To_v2_ServiceMonitor(in *v1.ServiceMonitor, out *ServiceMonitor, s conversion.Scope) error {
	return autoConvert_v1_ServiceMonitor_To_v2_ServiceMonitor(in, out, s)
}

func autoConvert_v2_ServiceMonitorList_To_v1_ServiceMonitorList(in *ServiceMonitorList, out *v1.ServiceMonitorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]*v1.ServiceMonitor)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v2_ServiceMonitorList_To_v1_ServiceMonitorList is an autogenerated conversion function.
func Convert_v2_ServiceMonitorList_To_v1_ServiceMonitorList(in *ServiceMonitorList, out *v1.ServiceMonitorList, s conversion.Scope) error {
	return autoConvert_v2_ServiceMonitorList_To_v1_ServiceMonitorList(in, out, s)
}

func autoConvert_v1_ServiceMonitorList_To_v2_ServiceMonitorList(in *v1.ServiceMonitorList, out *ServiceMonitorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]*ServiceMonitor)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_ServiceMonitorList_To_v2_ServiceMonitorList is an autogenerated conversion function.
func Convert_v1_ServiceMonitorList_To_v2_ServiceMonitorList(in *v1.ServiceMonitorList, out *ServiceMonitorList, s conversion.Scope) error {
	return autoConvert_v1_ServiceMonitorList_To_v2_ServiceMonitorList(in, out, s)
}

func autoConvert_v2_ServiceMonitorSpec_To_v1_ServiceMonitorSpec(in *ServiceMonitorSpec, out *v1.ServiceMonitorSpec, s conversion.Scope) error {
	out.JobLabel = in.JobLabel
	out.Endpoints = *(*[]v1.Endpoint)(unsafe.Pointer(&in.Endpoints))
	out.Selector = in.Selector
	if err := Convert_v2_NamespaceSelector_To_v1_NamespaceSelector(&in.NamespaceSelector, &out.NamespaceSelector, s); err != nil {
		return err
	}
	return nil
}

// Convert_v2_ServiceMonitorSpec_To_v1_ServiceMonitorSpec is an autogenerated conversion function.
func Convert_v2_ServiceMonitorSpec_To_v1_ServiceMonitorSpec(in *ServiceMonitorSpec, out *v1.ServiceMonitorSpec, s conversion.Scope) error {
	return autoConvert_v2_ServiceMonitorSpec_To_v1_ServiceMonitorSpec(in, out, s)
}

func autoConvert_v1_ServiceMonitorSpec_To_v2_ServiceMonitorSpec(in *v1.ServiceMonitorSpec, out *ServiceMonitorSpec, s conversion.Scope) error {
	out.JobLabel = in.JobLabel
	out.Endpoints = *(*[]Endpoint)(unsafe.Pointer(&in.Endpoints))
	out.Selector = in.Selector
	if err := Convert_v1_NamespaceSelector_To_v2_NamespaceSelector(&in.NamespaceSelector, &out.NamespaceSelector, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_ServiceMonitorSpec_To_v2_ServiceMonitorSpec is an autogenerated conversion function.
func Convert_v1_ServiceMonitorSpec_To_v2_ServiceMonitorSpec(in *v1.ServiceMonitorSpec, out *ServiceMonitorSpec, s conversion.Scope) error {
	return autoConvert_v1_ServiceMonitorSpec_To_v2_ServiceMonitorSpec(in, out, s)
}

func autoConvert_v2_StorageSpec_To_v1_StorageSpec(in *StorageSpec, out *v1.StorageSpec, s conversion.Scope) error {
	out.Class = in.Class
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Resources = in.Resources
	out.VolumeClaimTemplate = in.VolumeClaimTemplate
	return nil
}

// Convert_v2_StorageSpec_To_v1_StorageSpec is an autogenerated conversion function.
func Convert_v2_StorageSpec_To_v1_StorageSpec(in *StorageSpec, out *v1.StorageSpec, s conversion.Scope) error {
	return autoConvert_v2_StorageSpec_To_v1_StorageSpec(in, out, s)
}

func autoConvert_v1_StorageSpec_To_v2_StorageSpec(in *v1.StorageSpec, out *StorageSpec, s conversion.Scope) error {
	out.Class = in.Class
	out.Selector = (*meta_v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.Resources = in.Resources
	out.VolumeClaimTemplate = in.VolumeClaimTemplate
	return nil
}

// Convert_v1_StorageSpec_To_v2_StorageSpec is an autogenerated conversion function.
func Convert_v1_StorageSpec_To_v2_StorageSpec(in *v1.StorageSpec, out *StorageSpec, s conversion.Scope) error {
	return autoConvert_v1_StorageSpec_To_v2_StorageSpec(in, out, s)
}

func autoConvert_v2_TLSConfig_To_v1_TLSConfig(in *TLSConfig, out *v1.TLSConfig, s conversion.Scope) error {
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	out.ServerName = in.ServerName
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v2_TLSConfig_To_v1_TLSConfig is an autogenerated conversion function.
func Convert_v2_TLSConfig_To_v1_TLSConfig(in *TLSConfig, out *v1.TLSConfig, s conversion.Scope) error {
	return autoConvert_v2_TLSConfig_To_v1_TLSConfig(in, out, s)
}

func autoConvert_v1_TLSConfig_To_v2_TLSConfig(in *v1.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	out.ServerName = in.ServerName
	out.InsecureSkipVerify = in.InsecureSkipVerify
	return nil
}

// Convert_v1_TLSConfig_To_v2_TLSConfig is an autogenerated conversion function.
func Convert_v1_TLSConfig_To_v2_TLSConfig(in *v1.TLSConfig, out *TLSConfig, s conversion.Scope) error {
	return autoConvert_v1_TLSConfig_To_v2_TLSConfig(in, out, s)
}
